# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- gui

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8.3'
    addToPath: true
    architecture: 'x64'
  displayName: Install Python

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    failOnStderr: false
    script: |
      python -m pip install --upgrade pip
      python -m pip install wheel
      python -m pip install -r ./BeatMapSynthesizer/build/scripts/requirements.txt
      python -m pip install https://github.com/pyinstaller/pyinstaller/tarball/develop
      python -m pip install https://github.com/librosa/librosa/zipball/master
      $pyPath = python -c "import sys; print(sys.executable)"
      $pyPath = Split-Path -Path $pyPath
      $pyPath = Join-Path -Path $pyPath -ChildPath "Scripts\pywin32_postinstall.py"
      python $pyPath -install
  displayName: Install packages

- script: |
    npm install
    tsc --build
    yarn pack
  displayName: 'Build app'
